query fetchOrderDetail($id: ID!){
  order(id: $id){
    id
    good{
      id
      name
      description
      avatar
      price
    }
    addressId
    insertedAt
    number
    amount
    status
    address {
      id
      detail
    }
  }
}