query fetchCurrentOrders($oFilter: FilterOrderInput){
  currentUser {
    id
    orders(filter: $oFilter) {
    id
    good{
      id
      name
      description
      insertedAt
      avatar
      price
    }
    amount   
    number
    status
    }
    orders{
      id
    }
  }
  
}