query fetchCurrentOrders($oFilter: FilterOrderInput,$order:[OrderInput]){
  currentUser {
    id
    orders(filter: $oFilter,order:$order) {
    id
    insertedAt
    good{
      id
      name
      description
      insertedAt
      avatar
      price
    }
    amount   
    number
    status
    }
  }
}