query fetchShoppingBaseInfo($goodId: ID!){
  good(id: $goodId){
    id
    name
    description
    price
  }
  currentUser{
    id
    addresses {
      id
      name
      cellphone
      province
      city
      distinct
      detail
    }
  }
}