query fetchShoppingBaseInfo($goodId: ID!){
  currentUser{
    addresses {
      id
      name
      cellphone
      province
      city
      distinct
      detail
    }
  }
  good(id: $goodId){
    id
    name
    description
    price
  }
}